default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: tstesm3e
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: reddit_bookmark_catalog_development
  username: postgres
  password: tstesm3e
  host: 127.0.0.1
  post: 5432

test:
  <<: *default
  database: reddit_bookmark_catalog_test

production:
  <<: *default
  database: reddit_bookmark_catalog_production
